# Generated by Django 2.2.12 on 2022-07-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continents_field', models.CharField(choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('NorthAmerica', 'NorthAmerica'), ('Antarctica', 'Antarctica'), ('Europe', 'Europe'), ('Australia', 'Australia')], default='Asia', max_length=100)),
            ],
        ),
    ]
