# Generated by Django 2.2.12 on 2022-07-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='continents_field',
            field=models.CharField(default='Asia', max_length=100),
        ),
    ]
