# Generated by Django 2.2.12 on 2022-07-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_auto_20220716_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoilday_ref', models.CharField(max_length=100)),
                ('HotelName', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=100)),
                ('Continent', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('StarRating', models.CharField(max_length=100)),
                ('TempRating', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('PricePerPerNight', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='countries',
            name='continent',
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
