# Generated by Django 2.2.12 on 2022-07-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_auto_20220716_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continents_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holidays.Holiday')),
            ],
        ),
    ]
