# Generated by Django 2.2.12 on 2022-07-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0006_auto_20220717_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeholiday',
            old_name='continent',
            new_name='holiday',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='Category',
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=100)),
                ('holiday', models.ManyToManyField(to='holidays.Holiday')),
            ],
        ),
    ]
