# Generated by Django 2.2.12 on 2022-07-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0007_auto_20220717_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeholiday',
            old_name='holiday',
            new_name='holiday_details',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='Continent',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='TempRating',
        ),
        migrations.AddField(
            model_name='africacountries',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
        migrations.AddField(
            model_name='antarcticacountries',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
        migrations.AddField(
            model_name='asiacountries',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
        migrations.AddField(
            model_name='australiacountries',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
        migrations.AddField(
            model_name='europecountries',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
        migrations.AddField(
            model_name='northamericacountries',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
    ]
