# Generated by Django 2.2.12 on 2022-07-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0010_africacountries_antarcticacountries_asiacountries_australiacountries_continent_europecountries_north'),
    ]

    operations = [
        migrations.AddField(
            model_name='africacountries',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
    ]
