# Generated by Django 2.2.12 on 2022-07-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0011_africacountries_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='antarcticacountries',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
        migrations.AddField(
            model_name='asiacountries',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
        migrations.AddField(
            model_name='australiacountries',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
        migrations.AddField(
            model_name='europecountries',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
        migrations.AddField(
            model_name='northamericacountries',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
    ]
