# Generated by Django 2.2.12 on 2022-07-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0012_auto_20220717_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_hol', models.CharField(max_length=100)),
            ],
        ),
    ]
