# Generated by Django 2.2.12 on 2022-07-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0015_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeHol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_hol', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='result',
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
        migrations.DeleteModel(
            name='TypeHoliday',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='continents_field',
        ),
        migrations.AddField(
            model_name='holiday',
            name='continent',
            field=models.ManyToManyField(to='holidays.Continent'),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
