# Generated by Django 2.2.12 on 2022-07-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0016_auto_20220717_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeHol',
            new_name='TypeHoliday',
        ),
    ]
