# Generated by Django 2.2.12 on 2022-07-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0017_auto_20220717_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.IntegerField()),
            ],
        ),
    ]
