# Generated by Django 2.2.12 on 2022-07-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='FirstQuestion',
        ),
    ]
