# Generated by Django 2.2.12 on 2022-07-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20220716_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
