# Generated by Django 2.2.12 on 2022-07-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
