# Generated by Django 2.2.12 on 2022-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_auto_20220716_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Continents_field', models.ManyToManyField(to='countries.Question')),
            ],
        ),
    ]
