# Generated by Django 2.2.12 on 2022-07-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continent',
            name='Continents_field',
        ),
        migrations.AddField(
            model_name='continent',
            name='continents_field',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('NorthAmerica', 'NorthAmerica'), ('Antarctica', 'Antarctica'), ('Europe', 'Europe'), ('Australia', 'Australia')], default='Asia', max_length=100),
        ),
    ]
